# Generated by Django 4.2 on 2025-08-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام برند")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کالکشن")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collections/",
                        verbose_name="تصویر",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "کالکشن",
                "verbose_name_plural": "کالکشن\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام رنگ")),
                (
                    "hex_code",
                    models.CharField(
                        help_text="مثال: #FF0000",
                        max_length=7,
                        verbose_name="کد هگز رنگ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد محصول"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="قیمت با تخفیف",
                    ),
                ),
                (
                    "stock",
                    models.BooleanField(default=True, verbose_name="موجود در انبار"),
                ),
                (
                    "main_image",
                    models.ImageField(upload_to="products/", verbose_name="تصویر اصلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="root.brand",
                        verbose_name="برند",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="root.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="root.collection",
                        verbose_name="کالکشن",
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(to="root.color", verbose_name="رنگ\u200cها"),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="ReturnPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوای سیاست بازگشت")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "سیاست بازگشت",
                "verbose_name_plural": "سیاست\u200cهای بازگشت",
            },
        ),
        migrations.CreateModel(
            name="ShippingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="محتوای سیاست ارسال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "سیاست ارسال",
                "verbose_name_plural": "سیاست\u200cهای ارسال",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="نام سایز")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "سایز",
                "verbose_name_plural": "سایزها",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام تگ")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="اسلاگ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تگ",
                "verbose_name_plural": "تگ\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=100, verbose_name="نام کاربر"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="امتیاز",
                    ),
                ),
                ("comment", models.TextField(verbose_name="نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="root.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="کلید")),
                ("value", models.CharField(max_length=200, verbose_name="مقدار")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="root.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه فنی",
                "verbose_name_plural": "مشخصات فنی",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="تصویر"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="root.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
            },
        ),
        migrations.CreateModel(
            name="ProductFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=200, verbose_name="ویژگی")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="root.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی محصول",
                "verbose_name_plural": "ویژگی\u200cهای محصول",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(to="root.size", verbose_name="سایزها"),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="root.tag", verbose_name="تگ\u200cها"),
        ),
    ]
