# Generated by Django 4.2 on 2025-08-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("image", models.ImageField(upload_to="about/", verbose_name="تصویر")),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "بخش درباره ما",
                "verbose_name_plural": "بخش\u200cهای درباره ما",
                "ordering": ["order"],
            },
        ),
    ]
