# Generated by Django 4.2 on 2025-08-17 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0003_product_is_featured"),
        ("root", "0005_story"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name": "استوری", "verbose_name_plural": "استوری\u200cها"},
        ),
        migrations.AddField(
            model_name="story",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="stories/thumbnails/",
                verbose_name="تصویر بند انگشتی",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="caption",
            field=models.TextField(blank=True, verbose_name="کپشن"),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="story",
            name="file",
            field=models.FileField(upload_to="stories/", verbose_name="فایل"),
        ),
        migrations.AlterField(
            model_name="story",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="story",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=100, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
