# Generated by Django 4.2 on 2025-08-17 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_is_featured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("root", "0006_alter_story_options_story_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="story",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="story",
            name="caption",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="file",
            field=models.FileField(
                help_text="Upload image or video", upload_to="stories/"
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
