# Generated by Django 4.2 on 2025-08-14 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_is_new_product_sales_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "آدرس", "verbose_name_plural": "آدرس\u200cها"},
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "سبد خرید", "verbose_name_plural": "سبدهای خرید"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "آیتم سبد خرید",
                "verbose_name_plural": "آیتم\u200cهای سبد خرید",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.TextField(verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=50, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="نام کامل"),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="شماره تلفن"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=10, verbose_name="کد پستی"),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(max_length=50, verbose_name="استان"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شناسه جلسه"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.cart",
                verbose_name="سبد خرید",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.color",
                verbose_name="رنگ",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.size",
                verbose_name="سایز",
            ),
        ),
    ]
