# Generated by Django 4.2 on 2025-08-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_is_new_product_sales_count_and_more"),
        ("cart", "0002_alter_address_options_alter_cart_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="آدرس پیش\u200cفرض"),
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=100, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="نام کامل"),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="شماره تلفن"),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(max_length=20, verbose_name="کد پستی"),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(max_length=100, verbose_name="استان"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cartitem_set",
                to="cart.cart",
                verbose_name="سبد خرید",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.color",
                verbose_name="رنگ",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.size",
                verbose_name="سایز",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product", "color", "size")},
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="unique_cart_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_id__isnull", False)),
                fields=("session_id",),
                name="unique_cart_per_session",
            ),
        ),
    ]
