# Generated by Django 4.2 on 2025-08-14 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_product_is_new_product_sales_count_and_more"),
        ("cart", "0003_address_is_default_address_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="شماره سفارش"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="مبلغ کل"
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="تخفیف کل",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="هزینه ارسال",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="مبلغ نهایی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در حال پردازش"),
                            ("SHIPPED", "ارسال شده"),
                            ("DELIVERED", "تحویل شده"),
                            ("CANCELED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="شماره مرسوله",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="آنلاین", max_length=50, verbose_name="روش پرداخت"
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="کد رهگیری پرداخت",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="قیمت واحد"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="تخفیف"
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_cart_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_cart_per_session",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.color",
                verbose_name="رنگ",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderitems",
                to="cart.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="محصول",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.size",
                verbose_name="سایز",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cart.address",
                verbose_name="آدرس",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
