# Generated by Django 4.2 on 2025-08-14 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_product_is_new_product_sales_count_and_more"),
        ("cart", "0004_order_orderitem_remove_cart_unique_cart_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_time",
            field=models.CharField(
                default="۳ روز کاری", max_length=50, verbose_name="زمان تحویل"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                default="پست پیشتاز", max_length=50, verbose_name="روش ارسال"
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ افزودن"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه\u200cمندی",
                "verbose_name_plural": "علاقه\u200cمندی\u200cها",
                "unique_together": {("user", "product")},
            },
        ),
    ]
