# Generated by Django 4.2 on 2025-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_order_delivery_time_order_shipping_method_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=64, unique=True, verbose_name="شماره سفارش"
            ),
        ),
    ]
