# Generated by Django 4.2 on 2025-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="final_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="مبلغ نهایی"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="شماره سفارش"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="مبلغ کل"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="قیمت واحد"
            ),
        ),
    ]
