# Generated by Django 4.2 on 2025-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_order_final_price_alter_order_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="شماره سفارش"
            ),
        ),
    ]
