# Generated by Django 4.2 on 2025-08-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0009_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=64, unique=True, verbose_name="شماره سفارش"
            ),
        ),
    ]
