# Generated by Django 4.2 on 2025-08-13 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="اسلاگ"),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="قیمت با تخفیف",
                    ),
                ),
                (
                    "stock_status",
                    models.BooleanField(default=True, verbose_name="موجودی"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="دسته\u200cبندی"),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="برند")),
                (
                    "product_code",
                    models.CharField(max_length=50, verbose_name="کد محصول"),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="تگ\u200cها"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="نام سایز")),
                ("available", models.BooleanField(default=True, verbose_name="موجود")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سایز",
                "verbose_name_plural": "سایزها",
            },
        ),
        migrations.CreateModel(
            name="ShippingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_policies",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "سیاست ارسال",
                "verbose_name_plural": "سیاست\u200cهای ارسال",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="امتیاز",
                    ),
                ),
                ("comment", models.TextField(verbose_name="نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("value", models.CharField(max_length=200, verbose_name="مقدار")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصه فنی",
                "verbose_name_plural": "مشخصات فنی",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="تصویر"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="تصویر اصلی"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام رنگ")),
                ("hex_code", models.CharField(max_length=7, verbose_name="کد هگز رنگ")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colors",
                        to="products.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ\u200cها",
            },
        ),
    ]
