# Generated by Django 4.2 on 2025-08-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="جدید"),
        ),
        migrations.AddField(
            model_name="product",
            name="sales_count",
            field=models.IntegerField(default=0, verbose_name="تعداد فروش"),
        ),
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
    ]
