# Generated by Django 4.2 on 2025-08-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_is_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
    ]
